package com.orbious.util;

import com.orbious.util.Command;
import static org.hamcrest.CoreMatchers.*;
import static org.junit.Assert.*;
import org.junit.Test;

public class CommandTest {

	@Test
	public void type() throws Exception {
		// TODO auto-generated by JUnit Helper.
		assertThat(Command.class, notNullValue());
	}

	@Test
	public void instance_A$() throws Exception {
		// TODO auto-generated by JUnit Helper.
		Object actual = Command.instance();
		Object expected = null;
		assertThat(actual, is(equalTo(expected)));
	}

	@Test
	public void shutdown_A$() throws Exception {
		// TODO auto-generated by JUnit Helper.
		Command target = null;
		boolean actual = target.shutdown();
		boolean expected = false;
		assertThat(actual, is(equalTo(expected)));
	}

	@Test
	public void shutdown_A$boolean() throws Exception {
		// TODO auto-generated by JUnit Helper.
		Command target = null;
		boolean shutdown = false;
		target.shutdown(shutdown);
	}

	@Test
	public void canExit_A$() throws Exception {
		// TODO auto-generated by JUnit Helper.
		Command target = null;
		boolean actual = target.canExit();
		boolean expected = false;
		assertThat(actual, is(equalTo(expected)));
	}

	@Test
	public void canExit_A$boolean() throws Exception {
		// TODO auto-generated by JUnit Helper.
		Command target = null;
		boolean canExit = false;
		target.canExit(canExit);
	}

}
